dist: xenial
language: java
sudo: true
jdk: openjdk11
os: linux
install: true
cache:
  directories:
  - $HOME/.m2
  before_install:
    - chmod +x mvnw
  addons:
  apt:
    packages:
      - oracle-java11-installer
 